const images = [
    {
        id: 1,
        img: "https://i.ibb.co/djT9xMG/breakfast1.png",
        name: "Eggs Benedict",
        description: "How we dream about out future",
        price: 6.99,
    },
    {
        id: 2,
        img: "https://i.ibb.co/P9H8tCJ/breakfast2.png",
        name: "Breakfast sandwich",
        description: "How we dream about out future",
        price: 9.99,
    },
    {
        id: 3,
        img: "https://i.ibb.co/L905QH9/breakfast3.png",
        name: "Baked Chicken",
        description: "How we dream about out future",
        price: 10.99,
    },
    {
        id: 4,
        img: "https://i.ibb.co/2cQ2r3Y/breakfast4.png",
        name: "Bagel and cream cheese",
        description: "How we dream about out future",
        price: 6.99,
    },
    {
        id: 5,
        img: "https://i.ibb.co/5h8hprZ/breakfast5.png",
        name: "Breakfast Fried Egg Toast",
        description: "How we dream about out future",
        price: 3.99,
    },
    {
        id: 6,
        img: "https://i.ibb.co/KwjYpjz/breakfast6.png",
        name: "The Croissant Fried egg",
        description: "How we dream about out future",
        price: 19.99,
    },
    {
        id: 7,
        img: "https://i.ibb.co/HPpNzqT/lunch1.png",
        name: "Beef Steak",
        description: "How we dream about out future",
        price: 15.99,
    },
    {
        id: 8,
        img: "https://i.ibb.co/fNZ7Gjf/lunch2.png",
        name: "Honey-Soy-Glazed Salmon with Peppers",
        description: "How we dream about out future",
        price: 7.99,
    },
    {
        id: 9,
        img: "https://i.ibb.co/YLgjd1X/lunch3.png",
        name: "Tarragon-Rubbed-Salmon",
        description: "How we dream about out future",
        price: 19.99,
    },
    {
        id: 10,
        img: "https://i.ibb.co/hKFZvKL/lunch4.png",
        name: "Indian Lunch",
        description: "How we dream about out future",
        price: 12.99,
    },
    {
        id: 11,
        img: "https://i.ibb.co/B3CkkVS/lunch5.png",
        name: "Healthy Meal Plan",
        description: "How we dream about out future",
        price: 23.99,
    },
    {
        id: 12,
        img: "https://i.ibb.co/wNYkV2k/lunch6.png",
        name: "Fried Chicken Bento",
        description: "How we dream about out future",
        price: 19.99,
    },

    {
        id: 13,
        img: "  https://i.ibb.co/hW6TpfX/dinner1.png",
        name: "Baked Chicken",
        description: "How we dream about out future",
        price: 9.99,
    },
    {
        id: 14,
        img: "https://i.ibb.co/x1nfYJM/dinner2.png",
        name: "Lemon Salmon Piccata ",
        description: "How we dream about out future",
        price: 10.99,
    },
    {
        id: 15,
        img: "https://i.ibb.co/jfTRNvQ/dinner3.png ",
        name: "Garlic Butter Baked Salmon",
        description: "How we dream about out future",
        price: 19.99,
    },
    {
        id: 16,
        img: "https://i.ibb.co/0qK4zwL/dinner4.png",
        name: "French fries with cheese",
        description: "How we dream about out future",
        price: 8.99,
    },
    {
        id: 17,
        img: "https://i.ibb.co/pZ8GZRP/dinner5.png",
        name: "Pork Tenderloin with Quinoa pilaf",
        description: "How we dream about out future",
        price: 12.99,
    },
    {
        id: 18,
        img: "https://i.ibb.co/dfnZDjC/dinner6.png",
        name: "Salmon",
        description: "How we dream about out future",
        price: 19.99,
    },
]